### ISSUE TITLE
auth2.grantOfflineAcces error

### ISSUE THREAD

**Issue by leosaravia** [googleplus/gplus-quickstart-csharp#22]
I'm having the following exception: 

Uncaught TypeError: auth2.grantOfflineAccess is not a function
    at Object.reauthorize [as error] (index.html:280)

For what I could see looking about this error, is that the grantOfflineAccess Method really doesn´t exists... and I haven't been able to find a solution... 

Anyone have found a solution?

Thanks!

**Comment by leosaravia** [comment]
Nevermind, the error ocurred couse the startup function was never called, so only by adding it to the signInClick function at the start, it corrected all other errores(front ones at least).

**Comment by leosaravia** [comment]
Neverm

**Comment by gguuss** [comment]
This sample is deprecated, you should [check here](https://developers.google.com/identity/one-tap/web/overview) for an updated way of signing in.

**Comment by leosaravia** [comment]
Wow thanks! This example seems much easier than the one before.

Best regards

2018-02-15 15:41 GMT-03:00 Gus Class <notifications@github.com>:
